In [12]:
import numpy as np
import torch

a = torch.asarray([1])
print(a)
b = torch.asarray([0.,1.,2.])
c = torch.nn.functional.softmax(b / 3)
print(c)
d = torch.clamp(c, 0.01,0.99)
print(d)

tensor([1])
tensor([0.2302, 0.3213, 0.4484])
tensor([0.2302, 0.3213, 0.4484])


C:\Users\99san\AppData\Local\Temp\ipykernel_2364\957846762.py:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  c = torch.nn.functional.softmax(b / 3)


In [27]:
targets = [eval(i) for i in "1,2,3".split(',')]
print(targets * length(targets))

NameError: name 'length' is not defined

Distilled Dataset check

In [8]:
import os 
from torch.utils.data import Dataset
from PIL import Image
from torchvision import transforms 
class DistilledDataset(Dataset):
    def __init__(self, path):
        super().__init__()
        self.path = path
        self.data = []
        print('Loading distilled datasets from {} ...'.format(path))    
        for image in os.listdir(path):
            file = os.path.join(path, image)
            if os.path.isfile(file):
                class_id = eval(image.split('_')[0])
                self.data.append([file,class_id])
        
        
    def __getitem__(self, index):
        image = self.data[index][0]
        x = Image.open(image)
        y = self.data[index][1]
        
        return x, y
            
# test
path = './results/final_images/vgg11_inversion'
dataset = DistilledDataset(path, transform=transforms.Compose([transforms.ToTensor()]))
x,y = dataset.__getitem__(0)
print(x.shape)
print(y)

TypeError: DistilledDataset.__init__() got an unexpected keyword argument 'transform'