In [12]:
import numpy as np
import torch

a = torch.asarray([1])
print(a)
b = torch.asarray([0.,1.,2.])
c = torch.nn.functional.softmax(b / 3)
print(c)
d = torch.clamp(c, 0.01,0.99)
print(d)

tensor([1])
tensor([0.2302, 0.3213, 0.4484])
tensor([0.2302, 0.3213, 0.4484])


C:\Users\99san\AppData\Local\Temp\ipykernel_2364\957846762.py:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  c = torch.nn.functional.softmax(b / 3)


In [15]:
[10] + [1. for _ in range(2)]

[10, 1.0, 1.0]