In [12]:
import numpy as np
import torch

a = torch.asarray([1])
print(a)
b = torch.asarray([0.,1.,2.])
c = torch.nn.functional.softmax(b / 3)
print(c)
d = torch.clamp(c, 0.01,0.99)
print(d)

tensor([1])
tensor([0.2302, 0.3213, 0.4484])
tensor([0.2302, 0.3213, 0.4484])


C:\Users\99san\AppData\Local\Temp\ipykernel_2364\957846762.py:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  c = torch.nn.functional.softmax(b / 3)


In [27]:
targets = [eval(i) for i in "1,2,3".split(',')]
print(targets * length(targets))

NameError: name 'length' is not defined

Distilled Dataset check

In [8]:
import os 
from torch.utils.data import Dataset
from PIL import Image
from torchvision import transforms 
class DistilledDataset(Dataset):
    def __init__(self, path, transforms=None):
        super().__init__()
        self.path = path
        self.transforms=transforms
        self.data = []
        print('Loading distilled datasets from {} ...'.format(path))    
        for image in os.listdir(path):
            file = os.path.join(path, image)
            if os.path.isfile(file):
                class_id = eval(image.split('_')[0])
                self.data.append([file,class_id])
        
        
    def __getitem__(self, index):
        image = self.data[index][0]
        x = self.transforms(Image.open(image))
        y = self.data[index][1]
        
        return x, y
            
# test
path = './results/final_images/vgg11_inversion'
dataset = DistilledDataset(path, transforms=transforms.Compose([transforms.ToTensor()]))
dataset.__getitem__(0)[0]

Loading distilled datasets from ./results/final_images/vgg11_inversion ...


tensor([[[0.0078, 0.0000, 0.0118,  ..., 0.0000, 0.0000, 0.0000],
         [0.0078, 0.0314, 0.0039,  ..., 0.0706, 0.0706, 0.0510],
         [0.0039, 0.0039, 0.0157,  ..., 0.0275, 0.0510, 0.0000],
         ...,
         [0.0824, 0.1059, 0.1255,  ..., 0.3333, 0.2471, 0.0196],
         [0.1922, 0.2039, 0.2902,  ..., 0.3490, 0.1961, 0.0000],
         [0.2980, 0.3020, 0.4510,  ..., 0.3686, 0.2745, 0.1725]],

        [[0.0275, 0.0157, 0.0314,  ..., 0.0196, 0.0275, 0.0431],
         [0.0275, 0.0510, 0.0235,  ..., 0.1137, 0.1216, 0.1020],
         [0.0196, 0.0235, 0.0275,  ..., 0.0784, 0.1059, 0.0157],
         ...,
         [0.0667, 0.0824, 0.0902,  ..., 0.3686, 0.2863, 0.0627],
         [0.1725, 0.1765, 0.2471,  ..., 0.4000, 0.2588, 0.0510],
         [0.2784, 0.2784, 0.4118,  ..., 0.4314, 0.3451, 0.2471]],

        [[0.0431, 0.0314, 0.0471,  ..., 0.0431, 0.0510, 0.0667],
         [0.0510, 0.0667, 0.0471,  ..., 0.1373, 0.1451, 0.1255],
         [0.0549, 0.0471, 0.0627,  ..., 0.1020, 0.1176, 0.

In [34]:
import torch
input = torch.Tensor()
img1 = torch.unsqueeze(torch.rand(3,32,32),0)
img2 = torch.unsqueeze(torch.rand(3,32,32),0)
print(img1.shape)
input = torch.cat((input, img1))
print(input.shape)
input = torch.cat((input, img2))
print(input.shape)

torch.Size([1, 3, 32, 32])
torch.Size([1, 3, 32, 32])
torch.Size([2, 3, 32, 32])


In [ ]:
train_dataset